### ISSUE TITLE
paste delay

### ISSUE THREAD

**Issue by MattC8915** [anotherchrisberry/textentered#3]
I've played around with different values for pasteDelay and regardless of what I send in, the paste is still taking place after the line that sets var fieldValue - so fieldValue doesn't contain what is pasted. However, if I surround lines 46-53 with setTimeout of 0 it works.

    setTimeout(function() {
        var fieldValue = $data.trimValue ? $.trim($this.val()) : $this.val();
        if (fieldValue != $data.lastValue) {
            setTimeout(
                function() {
                    $this.textentered('detectIdle', eventVersion);
                },$data.idleDelay);
    }, 0);
        
 Would this be an acceptable change?
 Or the     0 could be $data.pasteDelay

**Comment by anotherchrisberry** [comment]
Hey Matt,

It's been a few years since I've looked at this code, honestly. I'll dig into it tonight and check it out.

**Comment by MattC8915** [comment]
Great, thanks

**Comment by anotherchrisberry** [comment]
Hi Matt,

Which browser/OS are you seeing this issue in? I threw together a quick test and the paste seems to be working, but I only checked in FF/Chrome on OSX

Demo: https://jsfiddle.net/d1fqdcfy/1/

**Comment by MattC8915** [comment]
Windows 7 firefox and chrome. Using that demo, the text only shows up in the result after I click somewhere else and the textbox loses focus.

**Comment by MattC8915** [comment]
or typing another letter after the paste

**Comment by anotherchrisberry** [comment]
Okay, looks like jQuery doesn't respond immediately to the paste event if it's done via mouse - I updated the set of events it listens to, adding the following:
 * `input`
 * `propertychange`

Give it a shot (https://jsfiddle.net/d1fqdcfy/3/) and see if that solves the problem - it is working for me in Chrome and IE10 on Windows 7 and Chrome on OSX.

**Comment by MattC8915** [comment]
Yep, that's working great. Appreciate it
